services:
  localstack:
    image: localstack/localstack:4.4.0
    container_name: localstack-aws
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3,dynamodb,iam,sts
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
